bind-key -r i run-shell "tmux neww cht"
set -g status-style 'bg=#333333 fg=#5eacd3'

set -g base-index 1
set-option -sg escape-time 10
set-option -g focus-events on
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

